#!/usr/bin/env python3
"""Auto-redirect wrapper - delegates to the actual implementation
located in .trae/skills/live2d-master-agent/live2d_agent.py.
Generated by root-level fix. Do not edit manually."""
import os, sys

# Fix Windows GBK terminal encoding for emoji output
if sys.stdout and hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
if sys.stderr and hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

_HERE = os.path.dirname(os.path.abspath(__file__))
_SKILL_DIR = os.path.join(_HERE, ".trae", "skills", "live2d-master-agent")
_ORIG_CWD = os.getcwd()

# Convert relative path arguments to absolute (before chdir)
_new_argv = [sys.argv[0]]
for _arg in sys.argv[1:]:
    if not _arg.startswith("-") and (os.path.exists(os.path.join(_ORIG_CWD, _arg)) or os.sep in _arg or "." in _arg):
        _abs = os.path.abspath(os.path.join(_ORIG_CWD, _arg))
        _new_argv.append(_abs)
    else:
        _new_argv.append(_arg)
sys.argv = _new_argv

os.chdir(_SKILL_DIR)
sys.argv[0] = "live2d_agent.py"
sys.path.insert(0, _SKILL_DIR)

with open(os.path.join(_SKILL_DIR, "live2d_agent.py"), "r", encoding="utf-8") as _f:
    _code = _f.read()
exec(compile(_code, os.path.join(_SKILL_DIR, "live2d_agent.py"), "exec"), {"__name__": "__main__", "__file__": os.path.join(_SKILL_DIR, "live2d_agent.py")})
