#!/usr/bin/env python3
"""Auto-redirect wrapper - delegates to the actual implementation
located in .trae/skills/live2d-master-agent/test_workflow.py.
Generated by root-level fix. Do not edit manually."""
import os
import sys

# Fix Windows GBK terminal encoding for emoji output
if sys.stdout and hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
if sys.stderr and hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

_HERE = os.path.dirname(os.path.abspath(__file__))
_SKILL_DIR = os.path.join(_HERE, ".trae", "skills", "live2d-master-agent")
_ORIG_CWD = os.getcwd()

if not os.path.isdir(_SKILL_DIR):
    print(f"[ERROR] Skill implementation not found: {_SKILL_DIR}", file=sys.stderr)
    print("[ERROR] Please clone the repository completely.", file=sys.stderr)
    sys.exit(1)

# Tell the skill where the project root is so outputs/config go to the root
# directory when the user runs commands from the repository root.
os.environ.setdefault("LIVE2D_PROJECT_ROOT", _HERE)
os.environ.setdefault("LIVE2D_SKILL_DIR", _SKILL_DIR)

# Convert relative path arguments to absolute (before chdir)
_new_argv = [sys.argv[0]]
for _arg in sys.argv[1:]:
    if not _arg.startswith("-") and (
        os.path.exists(os.path.join(_ORIG_CWD, _arg))
        or os.sep in _arg
    ):
        _new_argv.append(os.path.abspath(os.path.join(_ORIG_CWD, _arg)))
    else:
        _new_argv.append(_arg)
sys.argv = _new_argv

os.chdir(_SKILL_DIR)
sys.argv[0] = "test_workflow.py"
sys.path.insert(0, _SKILL_DIR)

_target = os.path.join(_SKILL_DIR, "test_workflow.py")
with open(_target, "r", encoding="utf-8") as _f:
    _code = _f.read()
exec(compile(_code, _target, "exec"), {"__name__": "__main__", "__file__": _target})
