#!/usr/bin/env python3
"""
__PET_NAME__ - AI Desktop Pet
Generated by AI Pet Generator

Controls:
  Left-click pet   -> Happy expression
  Drag pet         -> Move to position
  Right-click/ESC  -> Exit
"""

import os
import sys
import math
import random
import time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
LAYERS_DIR = os.path.join(SCRIPT_DIR, "layers")
CONFIG_PATH = os.path.join(SCRIPT_DIR, "pet_config.json")
os.chdir(SCRIPT_DIR)

import json
import pygame

def load_config():
    try:
        with open(CONFIG_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {
            "name": "__PET_NAME__",
            "canvas_size": [256, 384],
            "fps": 60,
            "layer_groups": {},
            "animations": {
                "body_swing_amplitude": 3.0,
                "body_swing_speed": 0.8,
                "breath_amplitude": 1.5,
                "breath_speed": 0.4,
                "blink_interval_min": 3.0,
                "blink_interval_max": 6.0,
                "blink_duration": 0.15,
                "hair_swing_multiplier": 1.8,
                "expression_change_interval": 10.0,
            }
        }

def load_layers(layers_dir):
    layers = []
    if not os.path.isdir(layers_dir):
        return [create_default_pet_layer()]
    for fname in sorted(os.listdir(layers_dir)):
        if fname.endswith(".png"):
            path = os.path.join(layers_dir, fname)
            try:
                surf = pygame.image.load(path).convert_alpha()
                layers.append((fname, surf))
            except Exception:
                pass
    return layers if layers else [create_default_pet_layer()]

def get_layer_group(fname, layer_groups):
    """Determine animation group for a layer using config mapping.
    Falls back to keyword matching if no config mapping found.
    """
    name_no_ext = os.path.splitext(fname)[0].lower()
    for group, names in layer_groups.items():
        for n in names:
            if n.lower() == name_no_ext or n.lower() in name_no_ext:
                return group
    keywords = {
        "hair_front": ["hair", "bangs", "ahoge", "sidehair", "头发"],
        "eyes": ["eye", "iris", "pupil", "highlight", "眼睛"],
        "mouth": ["mouth", "lip", "teeth", "tongue", "嘴巴"],
        "eyebrows": ["eyebrow", "brow", "眉毛"],
        "face": ["face", "skin", "nose", "ear", "blush", "脸", "皮肤"],
        "body_swing": ["body", "chest", "clothes", "torso", "waist", "衣服", "身体"],
        "body_static": ["body_static", "shadow", "阴影"],
    }
    for group, kws in keywords.items():
        for kw in kws:
            if kw in name_no_ext:
                return group
    return "body_static"

def create_default_pet_layer():
    surf = pygame.Surface((128, 128), pygame.SRCALPHA)
    pygame.draw.circle(surf, (255, 200, 200), (64, 64), 50)
    pygame.draw.circle(surf, (100, 100, 200), (48, 54), 8)
    pygame.draw.circle(surf, (100, 100, 200), (80, 54), 8)
    pygame.draw.circle(surf, (255, 150, 150), (64, 75), 12, 2)
    return ("default", surf)

def clamp(val, low, high):
    return max(low, min(high, val))

def main():
    pygame.init()
    config = load_config()
    w, h = config.get("canvas_size", [256, 384])
    fps = config.get("fps", 60)
    anim = config.get("animations", {})

    screen = pygame.display.set_mode((w, h), pygame.NOFRAME | pygame.SRCALPHA)
    pygame.display.set_caption(config.get("name", "__PET_NAME__"))

    clock = pygame.time.Clock()
    layers = load_layers(LAYERS_DIR)

    info = pygame.display.Info()
    screen_w, screen_h = info.current_w, info.current_h
    pet_x = clamp(screen_w // 2 - w // 2, 0, max(0, screen_w - w))
    pet_y = clamp(screen_h - h - 100, 0, max(0, screen_h - h))

    start_time = time.time()
    next_blink = start_time + random.uniform(
        anim.get("blink_interval_min", 3),
        anim.get("blink_interval_max", 6))
    blink_until = 0
    next_expression = start_time + anim.get("expression_change_interval", 10)
    next_move = start_time + 10
    expression = "normal"
    dragging = False
    drag_offset = (0, 0)

    running = True
    while running:
        now = time.time()
        t = now - start_time
        dt = clock.tick(fps) / 1000.0

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
            elif event.type == pygame.MOUSEBUTTONDOWN:
                if event.button == 1:
                    mx, my = event.pos
                    dragging = True
                    drag_offset = (mx - pet_x, my - pet_y)
                    expression = "happy"
                    next_expression = now + 2
                elif event.button == 3:
                    running = False
            elif event.type == pygame.MOUSEBUTTONUP:
                if event.button == 1:
                    dragging = False
            elif event.type == pygame.MOUSEMOTION:
                if dragging:
                    mx, my = event.pos
                    pet_x = clamp(mx - drag_offset[0], 0, max(0, screen_w - w))
                    pet_y = clamp(my - drag_offset[1], 0, max(0, screen_h - h))

        if now > next_move and not dragging:
            max_x = max(50, screen_w - w - 50)
            pet_x = random.randint(min(50, max_x), max_x)
            next_move = now + random.uniform(8, 15)

        eye_open = 1.0
        if now < blink_until:
            blink_progress = (blink_until - now) / anim.get("blink_duration", 0.15)
            eye_open = blink_progress
        elif now > next_blink:
            blink_until = now + anim.get("blink_duration", 0.15)
            next_blink = now + random.uniform(
                anim.get("blink_interval_min", 3),
                anim.get("blink_interval_max", 6))

        if now > next_expression:
            expression = random.choice(["normal", "happy", "shy", "normal", "normal"])
            next_expression = now + random.uniform(8, 15)

        screen.fill((0, 0, 0, 0))

        swing = math.sin(t * anim.get("body_swing_speed", 0.8)) * anim.get("body_swing_amplitude", 3)
        breath = math.sin(t * anim.get("breath_speed", 0.4)) * anim.get("breath_amplitude", 1.5)
        hair_swing = swing * anim.get("hair_swing_multiplier", 1.8)

        layer_groups = config.get("layer_groups", {})
        for name, surf in layers:
            group = get_layer_group(name, layer_groups)
            offset_x, offset_y = 0, breath

            if group == "hair_front" or group == "hair_back":
                offset_x = hair_swing
            elif group == "body_swing":
                offset_x = swing * 0.5

            draw_surf = surf
            if eye_open < 0.9 and group == "eyes":
                sw, sh = surf.get_size()
                new_h = max(1, int(sh * eye_open))
                draw_surf = pygame.transform.scale(surf, (sw, new_h))
                offset_y += (sh - new_h) // 2

            screen.blit(draw_surf, (pet_x + offset_x, pet_y + offset_y))

        pygame.display.flip()

    pygame.quit()

if __name__ == "__main__":
    main()
